### ISSUE TITLE
show example for calculating renko candles on heiken ashi

### ISSUE THREAD

**Issue by pannet1** [mr-easy/streaming_indicators#2]
@mr-easy i will make an attempt and post the gist. can you please post the methods to be used.

**Comment by mr-easy** [comment]
As per my understanding of Renko, bricks are formed real-time as and when the price difference crosses the brick size, eg if last brick was formed at price:100 and brick size is set to 10, then next green brick will be formed as soon as price touches 110. So, ideal renko is computed using tick data.

But since mostly tick data is not available, candles close is used. The finer the timeframe of candles, the more accurate the bricks will be. Here 'accurate' means according to Renko logic, and does not imply that a finer timeframe is better or worse for trading.

Now if you want to compute Renko using Heikin Ashi candles, then that can also be done, but remember that it won't match with Renko bricks available on other trading platforms.
```
HA = si.HeikinAshi()
brick_size = 2
Renko = si.Renko()
for idx, candle in candles.iterrows():
    ha_candle = HA.update(candle)
    print("HA:", ha_candle) # {'close': float, 'open': float, 'high': float, 'low': float}
    bricks = Renko.update(ha_candle['close'], brick_size)
    print("RENKO:", bricks) # [{'direction': 1/-1, 'brick_num': int, 'wick_size': float, 'brick_size': float, 'brick_end_price': float, 'price': float}, {...}, ...]: list of bricks formed after this candle's close price
```
One more thing, Renko is very much dependent on your starting price also. This is important because when you backtest something using Renko, it can change just based on what start time you used for computing Renko.

**Comment by pannet1** [comment]
thank you @mr-easy
